version: '3.9'

networks:
  book_crud:
    driver: bridge

volumes:
  node-modules:

services:
  next:
    image: book_crud_front
    container_name: book_crud_front
    build:
      context: .
      dockerfile: ./next/Dockerfile
    volumes:
      - ./next:/next
      - node-modules:/next/node_modules
    networks:
      - book_crud
    ports:
      - 3000:3000
    tty: true

  api:
    image: book_crud_api
    container_name: book_crud_api
    build:
      context: .
      dockerfile: ./go_api/Dockerfile
    networks:
      - book_crud
    ports:
      - 8000:8000
    tty: true